pipeline {
    agent any

    stages {

        stage('Setup') {
            steps {
                sh '''
                  cd lambda-app
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install --upgrade pip
                  pip install -r tests/requirements.txt
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                  cd lambda-app
                  . venv/bin/activate
                  pytest
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                  cd lambda-app
                  . venv/bin/activate
                  sam build -t template.yaml
                '''
            }
        }

        stage('Deploy') {
            environment {
                AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
            }
            steps {
                sh '''
                  cd lambda-app
                  . venv/bin/activate
                  sam deploy \
                    -t template.yaml \
                    --no-confirm-changeset \
                    --no-fail-on-empty-changeset
                '''
            }
        }
    }
}
