pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-server-ip')
    }

    stages {

        stage('Setup') {
            steps {
                dir('02-single-server-deployment') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('02-single-server-deployment') {
                    // pytest is installed under ~/.local/bin
                    sh '$HOME/.local/bin/pytest'
                }
            }
        }

        stage('Package code') {
            steps {
                dir('02-single-server-deployment') {
                    sh 'zip -r myapp.zip .'
                    sh 'ls -lart'
                }
            }
        }

        stage('Deploy to Prod') {
            steps {
                dir('02-single-server-deployment') {
                    withCredentials([
                        sshUserPrivateKey(
                            credentialsId: 'ssh-key',
                            keyFileVariable: 'MY_SSH_KEY',
                            usernameVariable: 'USERNAME'
                        )
                    ]) {
                        sh '''
                        scp -i $MY_SSH_KEY -o StrictHostKeyChecking=no myapp.zip ${USERNAME}@${SERVER_IP}:/home/ec2-user/

                        ssh -i $MY_SSH_KEY -o StrictHostKeyChecking=no ${USERNAME}@${SERVER_IP} << EOF
                          unzip -o /home/ec2-user/myapp.zip -d /home/ec2-user/app/
                          cd /home/ec2-user/app/
                          source venv/bin/activate
                          pip install -r requirements.txt
                          sudo systemctl restart flaskapp.service
EOF
                        '''
                    }
                }
            }
        }
    }
}
